@HostAddress = http://localhost:5102

### Copy within the same array

PATCH {{HostAddress}}/customers/1
Content-Type: application/json-patch+json

[
  {
    "op": "copy",
    "from": "/orders/0",
    "path": "/orders/1"
  }
]

### Try modifying an enum

PATCH {{HostAddress}}/customers/2
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "/customerType",
    "value": "Regular"
  }
]


### test-fail.json

PATCH {{HostAddress}}/customers/1
Content-Type: application/json-patch+json

[
  {
    "op": "test",
    "path": "/customerName",
    "value": "Nancy"
  },
  {
    "op": "add",
    "path": "/customerName",
    "value": "Phil"
  }
]

### test-fail-2

PATCH {{HostAddress}}/customers/1
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "/customerName",
    "value": "Phil"
  },
  {
    "op": "test",
    "path": "/customerName",
    "value": "Nancy"
  }
]
