@HostAddress = http://localhost:5102

GET {{HostAddress}}/openapi/v1.json
Accept: application/json

### ListCustomers

GET {{HostAddress}}/customers
Accept: application/json

### GetCustomer

@id=5889b091-ebe9-40d9-9b21-9e9c14c796b6

GET {{HostAddress}}/customers/{{id}}
Accept: application/json

### CreateCustomer

POST {{HostAddress}}/customers
Content-Type: application/json

{
  "Name": "Jane Smith",
  "Email": "janesmith@gmail.com",
  "PhoneNumber": "987-654-3210",
  "Address": "456 Elm St, Othertown, USA",
  "Type": "Prime"
}

### DeleteCustomer

DELETE {{HostAddress}}/customers/{{id}}
Accept: application/json

### add.json

PATCH {{HostAddress}}/customers/{{id}}
Content-Type: application/json-patch+json

[
  {
    "op": "add",
    "path": "/orders/-",
    "value": {
      "orderDate": "2025-04-21T00:00:00Z",
      "totalAmount": 150.00
    }
  }
]

### copy.json

PATCH {{HostAddress}}/customers/{{id}}
Content-Type: application/json-patch+json

[
    {
    "op": "replace",
    "path": "/orders/0/shipDate",
    "value":  "2025-04-25T12:34:56Z"
  },
  {
    "op": "copy",
    "from": "/orders/0/shipDate",
    "path": "/orders/1/shipDate"
  }
]

### Try modifying an enum

PATCH {{HostAddress}}/customers/{{id}}
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "/type",
    "value": "Regular"
  }
]

### Replace

PATCH {{HostAddress}}/customers/{{id}}
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "/orders/0",
    "value": {
      "orderDate": "2025-04-21T12:12:12Z",
      "totalAmount": 250.00
    }
  }
]

### test-fail.json

PATCH {{HostAddress}}/customers/{{id}}
Content-Type: application/json-patch+json

[
  {
    "op": "test",
    "path": "/name",
    "value": "Nancy Jones"
  },
  {
    "op": "add",
    "path": "/name",
    "value": "Nancy James"
  }
]

### test-fail-2

PATCH {{HostAddress}}/customers/1
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "/name",
    "value": "Nancy Jones"
  },
  {
    "op": "test",
    "path": "/name",
    "value": "Nancy"
  }
]
